name: nmrium tag publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: |
          npm ci
      - name: Update version number
        run: |
          VERSION=${GITHUB_REF//*\/}
          echo "export default { version: '$VERSION' };" > src/versionInfo.ts
      - name: Build
        run: |
          rm src/demo/samples.json
          mv src/demo/empty.json src/demo/samples.json
          newPackage=$(jq 'setpath(["homepage"]; ".")' package.json)
          echo $newPackage > package.json
          npm run build
      - name: Remove spectra
        run: |
          rm -rf build/data
          rm -rf build/exercises
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
